insert into manager (name, last_name, team, past_position, total_minutes) values ('Αθανάσιος', 'Κεδίκογλου', 'AEK', 'Attacking Midfielder', 20491);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Λεωνίδας', 'Τσουκαλάς', 'Panathinaikos', 'Attacking Midfielder', 8919);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Λεωνίδας', 'Φανουράκης', 'PAOK', 'Center Back', 18034);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Ιωσήφ', 'Γιαλαμάς', 'Olympiacos', 'Center Back', 13727);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Δήμος', 'Κεχαγιάς', 'Aris', 'Attacking Midfielder', 28215);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Κλεάνθης', 'Φωτόπουλος', 'Volos', 'Right Back', 22881);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Απόστολος', 'Σκλαβούνος', 'Atromitos', 'Attacking Midfielder', 19642);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Αθανάσιος', 'Δασκαλάκης', 'Asteras Tripolis', 'Center Forward', 39523);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Ρωμανός', 'Διδασκάλου', 'OFI Crete', 'Center Forward', 23793);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Ιωσήφ', 'Φατμελής', 'PAS Giannina', 'Goal Keeper', 35865);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Αντώνης', 'Δημαράς', 'Ionikos', 'Center Back', 27649);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Κώστας', 'Ψωμιάδης', 'PAS Lamia', 'Left Midfielder', 1723);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Αθανάσιος', 'Δασκαλάκης', 'Panserraikos', 'Left Wing', 11137);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Δήμος', 'Διδασκάλου', 'AEL', 'Right Back', 38570);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Σωτήριος', 'Δέδες', 'Panetolikos', 'Defensive Midfielder', 5275);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Απόστολος', 'Βέλλος', 'Almopos Aridea', 'Center Forward', 18677);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Αθανάσιος', 'Γεωργιάδης', 'Egaleo', 'Defensive Midfielder', 3719);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Θωμάς', 'Δασκαλάκης', 'Apollon Smyrnis', 'Right Back', 4981);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Σωτήριος', 'Φανουράκης', 'Kalamata', 'Goal Keeper', 4631);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Σεραφείμ', 'Πολίτης', 'Kavala', 'Attacking Midfielder', 4949);
insert into manager (name, last_name, team, past_position, total_minutes) values ('Ισαάκ', 'Δελής', 'Levadiakos', 'Right Midfielder', 6514);
