insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('AEK', 'Panathinaikos', 2, 2, '4/8/2023',95 , 1);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('AEK', 'PAOK', 4, 2, '4/2/2023', 98, 2);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('AEK', 'Olympiacos', 1, 1, '5/29/2023', 102, 3);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('AEK', 'Aris', 1, 1, '4/15/2023', 109, 4);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('AEK', 'Volos', 0, 3, '4/26/2023',90, 5);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Panathinaikos', 'AEK', 1, 0, '5/8/2023',90, 6);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Panathinaikos', 'PAOK', 2, 1, '5/18/2023',95, 7);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Panathinaikos', 'Olympiacos', 2, 1, '5/1/2023',98, 8);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Panathinaikos', 'Aris', 3, 0, '4/26/2023',110, 9);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Panathinaikos', 'Volos', 3, 4, '5/1/2023',91, 10);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('PAOK', 'AEK', 3, 3, '4/19/2023',96, 11);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('PAOK', 'Panathinaikos', 0, 3, '4/16/2023',90, 12);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('PAOK', 'Olympiacos', 2, 2, '5/23/2023',90, 13);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('PAOK', 'Aris', 3, 4, '5/29/2023', 92, 14);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('PAOK', 'Volos', 4, 4, '4/12/2023', 86, 15);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Olympiacos', 'AEK', 0, 1, '5/28/2023', 93, 16);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Olympiacos', 'Panathinaikos', 2, 0, '4/23/2023',89, 17);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Olympiacos', 'PAOK', 2, 3, '5/16/2023',96, 18);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Olympiacos', 'Aris', 2, 1, '4/19/2023',100, 19);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Olympiacos', 'Volos', 4, 2, '4/14/2023',92, 20);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Aris', 'AEK', 2, 4, '5/27/2023',94, 21);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Aris', 'Panathinaikos', 4, 0, '4/29/2023',97,22);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Aris', 'PAOK', 2, 3, '4/27/2023',91, 23);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Aris', 'Olympiacos', 4, 4, '4/7/2023',89, 24);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Aris', 'Volos', 3, 4, '5/2/2023',93, 25);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration,id) values ('Volos', 'AEK', 0, 3, '4/26/2023',90, 26);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Volos', 'Panathinaikos', 4, 3, '4/1/2023',90, 27);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Volos', 'PAOK', 2, 3, '5/18/2023',104, 28);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Volos', 'Olympiacos', 1, 1, '5/8/2023',120, 29);
insert into match (home_team, visiting_team, home_score, visiting_score, date, total_duration, id) values ('Volos', 'Aris', 0, 1, '5/24/2023',91, 30);
