insert into player (name, last_name, team, position, minutes) values ('Αναστάσιος', 'Πέτσας', 'AEK', 'Left Wing', 834);
insert into player (name, last_name, team, position, minutes) values ('Πολύκαρπος', 'Σκλάβος', 'Panathinaikos', 'Left Midfielder', 3587);
insert into player (name, last_name, team, position, minutes) values ('Ιπποκράτης', 'Αλαφούζος', 'PAOK', 'Right Wing', 2146);
insert into player (name, last_name, team, position, minutes) values ('Λυκούργος', 'Δελής', 'Olympiacos', 'Center Forward', 4385);
insert into player (name, last_name, team, position, minutes) values ('Κίμων', 'Πέτσας', 'Aris', 'Right Back', 4957);
insert into player (name, last_name, team, position, minutes) values ('Αθανάσιος', 'Κονδύλης', 'Volos', 'Right Wing', 3647);
insert into player (name, last_name, team, position, minutes) values ('Πάρις', 'Φανουράκης', 'Atromitos', 'Goal Keeper', 2569);
insert into player (name, last_name, team, position, minutes) values ('Λάζαρος', 'Ψωμιάδης', 'Asteras Tripolis', 'Center Midfielder', 4151);
insert into player (name, last_name, team, position, minutes) values ('Δημήτρης', 'Κοκκινάκης', 'OFI Crete', 'Defensive Midfielder', 4956);
insert into player (name, last_name, team, position, minutes) values ('Σπύρος', 'Ανδρέου', 'PAS Giannina', 'Attacking Midfielder', 2872);
insert into player (name, last_name, team, position, minutes) values ('Αλέξανδρος', 'Φανουράκης', 'Ionikos', 'Center Midfielder', 78);
insert into player (name, last_name, team, position, minutes) values ('Ρομπέρτο', 'Κορομηλάς', 'PAS Lamia', 'Attacking Midfielder', 3474);
insert into player (name, last_name, team, position, minutes) values ('Ορφέας', 'Βούλγαρης', 'Panserraikos', 'Left Midfielder', 4210);
insert into player (name, last_name, team, position, minutes) values ('Σοφοκλής', 'Κοφινάς', 'AEL', 'Right Midfielder', 185);
insert into player (name, last_name, team, position, minutes) values ('Αντώνης', 'Σκυλακάκης', 'Panetolikos', 'Left Back', 870);
insert into player (name, last_name, team, position, minutes) values ('Βασίλης', 'Πάνου', 'Almopos Aridea', 'Goal Keeper', 1099);
insert into player (name, last_name, team, position, minutes) values ('Σεραφείμ', 'Ταμτάκος', 'Egaleo', 'Left Midfielder', 4606);
insert into player (name, last_name, team, position, minutes) values ('Χαρίτος', 'Κορομηλάς', 'Apollon Smyrnis', 'Left Back', 2921);
insert into player (name, last_name, team, position, minutes) values ('Στέφανος', 'Πάριος', 'Kalamata', 'Right Back', 521);
insert into player (name, last_name, team, position, minutes) values ('Νικόλαος', 'Πασαλίδης', 'Kavala', 'Right Wing', 1289);
insert into player (name, last_name, team, position, minutes) values ('Ρωμανός', 'Ανδρεάδης', 'Levadiakos', 'Left Wing', 946);
insert into player (name, last_name, team, position, minutes) values ('Σοφοκλής', 'Δενδρινός', 'AEK', 'Attacking Midfielder', 405);
insert into player (name, last_name, team, position, minutes) values ('Πολυζώης', 'Ιακωβίδης', 'Panathinaikos', 'Attacking Midfielder', 3482);
insert into player (name, last_name, team, position, minutes) values ('Θεοκλής', 'Τσακίρης', 'PAOK', 'Center Back', 2669);
insert into player (name, last_name, team, position, minutes) values ('Νικήτας', 'Βούρος', 'Olympiacos', 'Left Midfielder', 483);
insert into player (name, last_name, team, position, minutes) values ('Θεοφάνης', 'Ευθυμιάδης', 'Aris', 'Center Back', 422);
insert into player (name, last_name, team, position, minutes) values ('Ισαάκ', 'Πετράκος', 'Volos', 'Center Back', 2363);
insert into player (name, last_name, team, position, minutes) values ('Σοφοκλής', 'Πάριος', 'Atromitos', 'Defensive Midfielder', 753);
insert into player (name, last_name, team, position, minutes) values ('Αλέξανδρος', 'Αλιβιζάτος', 'Asteras Tripolis', 'Center Midfielder', 1295);
insert into player (name, last_name, team, position, minutes) values ('Κλεάνθης', 'Πάριος', 'OFI Crete', 'Right Midfielder', 3774);
insert into player (name, last_name, team, position, minutes) values ('Απόστολος', 'Αναστασίου', 'PAS Giannina', 'Left Wing', 4014);
insert into player (name, last_name, team, position, minutes) values ('Ιωάννης', 'Φλέσσας', 'Ionikos', 'Left Midfielder', 1388);
insert into player (name, last_name, team, position, minutes) values ('Θεοφάνης', 'Βουτσινάς', 'PAS Lamia', 'Center Forward', 3903);
insert into player (name, last_name, team, position, minutes) values ('Αθανάσιος', 'Βέλλος', 'Panserraikos', 'Right Wing', 1896);
insert into player (name, last_name, team, position, minutes) values ('Σοφοκλής', 'Ανδρέου', 'AEL', 'Center Midfielder', 2854);
insert into player (name, last_name, team, position, minutes) values ('Αντώνης', 'Γιαλαμάς', 'Panetolikos', 'Center Forward', 3739);
insert into player (name, last_name, team, position, minutes) values ('Δαμιανός', 'Πανταζής', 'Almopos Aridea', 'Left Back', 1024);
insert into player (name, last_name, team, position, minutes) values ('Σαράντος', 'Φατμελής', 'Egaleo', 'Right Midfielder', 73);
insert into player (name, last_name, team, position, minutes) values ('Θεοκλής', 'Ιακωβίδης', 'Apollon Smyrnis', 'Left Midfielder', 3871);
insert into player (name, last_name, team, position, minutes) values ('Δαμιανός', 'Κεχαγιάς', 'Kalamata', 'Left Midfielder', 2904);
insert into player (name, last_name, team, position, minutes) values ('Οδυσσέας', 'Φατμελής', 'Kavala', 'Right Midfielder', 1933);
insert into player (name, last_name, team, position, minutes) values ('Στέφανος', 'Δημαράς', 'Levadiakos', 'Center Midfielder', 2257);
insert into player (name, last_name, team, position, minutes) values ('Αναστάσιος', 'Κεχαγιάς', 'AEK', 'Left Wing', 4049);
insert into player (name, last_name, team, position, minutes) values ('Αναστάσιος', 'Αλεξίου', 'Panathinaikos', 'Left Back', 4700);
insert into player (name, last_name, team, position, minutes) values ('Σπύρος', 'Κεχαγιά', 'PAOK', 'Center Back', 4605);
insert into player (name, last_name, team, position, minutes) values ('Παναγιώτης', 'Βουτσινάς', 'Olympiacos', 'Left Midfielder', 2811);
insert into player (name, last_name, team, position, minutes) values ('Αλέξιος', 'Σκλάβος', 'Aris', 'Right Wing', 3326);
insert into player (name, last_name, team, position, minutes) values ('Αλέξανδρος', 'Τσόκος', 'Volos', 'Left Back', 1094);
insert into player (name, last_name, team, position, minutes) values ('Πολυζώης', 'Πυλαρινός', 'Atromitos', 'Right Midfielder', 28);
insert into player (name, last_name, team, position, minutes) values ('Ιωάννης', 'Πάριος', 'Asteras Tripolis', 'Left Wing', 3633);
insert into player (name, last_name, team, position, minutes) values ('Νικόλαος', 'Παναγούλης', 'OFI Crete', 'Attacking Midfielder', 2743);
insert into player (name, last_name, team, position, minutes) values ('Λυκούργος', 'Δημαράς', 'PAS Giannina', 'Left Wing', 2670);
insert into player (name, last_name, team, position, minutes) values ('Αλέξανδρος', 'Πέτσας', 'Ionikos', 'Goal Keeper', 796);
insert into player (name, last_name, team, position, minutes) values ('Απόστολος', 'Πετράκος', 'PAS Lamia', 'Center Forward', 2782);
insert into player (name, last_name, team, position, minutes) values ('Ιπποκράτης', 'Κοφινάς', 'Panserraikos', 'Goal Keeper', 2529);
insert into player (name, last_name, team, position, minutes) values ('Άγγελος', 'Κορνάρος', 'AEL', 'Attacking Midfielder', 4343);
insert into player (name, last_name, team, position, minutes) values ('Αχιλλέας', 'Σπανού', 'Panetolikos', 'Center Forward', 628);
insert into player (name, last_name, team, position, minutes) values ('Θωμάς', 'Κυπραίος', 'Almopos Aridea', 'Center Forward', 2747);
insert into player (name, last_name, team, position, minutes) values ('Κλέαρχος', 'Τσακίρης', 'Egaleo', 'Attacking Midfielder', 3917);
insert into player (name, last_name, team, position, minutes) values ('Σόλων', 'Δενδρινός', 'Apollon Smyrnis', 'Center Midfielder', 1985);
insert into player (name, last_name, team, position, minutes) values ('Σεραφείμ', 'Κορνάρος', 'Kalamata', 'Center Back', 110);
insert into player (name, last_name, team, position, minutes) values ('Δαμιανός', 'Ιακωβίδης', 'Kavala', 'Left Back', 98);
insert into player (name, last_name, team, position, minutes) values ('Σπύρος', 'Πάριος', 'Levadiakos', 'Left Wing', 2361);
insert into player (name, last_name, team, position, minutes) values ('Κλεάνθης', 'Φλέσσας', 'AEK', 'Center Forward', 1380);
insert into player (name, last_name, team, position, minutes) values ('Πολύκαρπος', 'Πασαλίδης', 'Panathinaikos', 'Left Back', 29);
insert into player (name, last_name, team, position, minutes) values ('Σεραφείμ', 'Διδασκάλου', 'PAOK', 'Goal Keeper', 2796);
insert into player (name, last_name, team, position, minutes) values ('Θωμάς', 'Δέδες', 'Olympiacos', 'Right Midfielder', 3821);
insert into player (name, last_name, team, position, minutes) values ('Πάρις', 'Κοκκινάκης', 'Aris', 'Right Back', 2817);
insert into player (name, last_name, team, position, minutes) values ('Θεοφάνης', 'Δέδες', 'Volos', 'Right Back', 639);
insert into player (name, last_name, team, position, minutes) values ('Κίμων', 'Σκαρβέλης', 'Atromitos', 'Left Wing', 1778);
insert into player (name, last_name, team, position, minutes) values ('Γεώργιος', 'Τσόκος', 'Asteras Tripolis', 'Right Wing', 2412);
insert into player (name, last_name, team, position, minutes) values ('Σοφοκλής', 'Αντωνιάδης', 'OFI Crete', 'Center Midfielder', 979);
insert into player (name, last_name, team, position, minutes) values ('Βασίλης', 'Πασαλίδης', 'PAS Giannina', 'Attacking Midfielder', 2567);
insert into player (name, last_name, team, position, minutes) values ('Σαράντος', 'Φωτόπουλος', 'Ionikos', 'Right Wing', 342);
insert into player (name, last_name, team, position, minutes) values ('Θεοφάνης', 'Κορωναίος', 'PAS Lamia', 'Defensive Midfielder', 1621);
insert into player (name, last_name, team, position, minutes) values ('Χαρίλαος', 'Κολιάτσος', 'Panserraikos', 'Center Midfielder', 3649);
insert into player (name, last_name, team, position, minutes) values ('Αλέξανδρος', 'Ευθυμιάδης', 'AEL', 'Left Wing', 4075);
insert into player (name, last_name, team, position, minutes) values ('Κώστας', 'Γερμανού', 'Panetolikos', 'Right Midfielder', 659);
insert into player (name, last_name, team, position, minutes) values ('Πέτρος', 'Πασαλίδης', 'Almopos Aridea', 'Center Midfielder', 637);
insert into player (name, last_name, team, position, minutes) values ('Ιωάννης', 'Παναγούλης', 'Egaleo', 'Defensive Midfielder', 1332);
insert into player (name, last_name, team, position, minutes) values ('Λάζαρος', 'Ευγενίδης', 'Apollon Smyrnis', 'Right Back', 580);
insert into player (name, last_name, team, position, minutes) values ('Πάρις', 'Βουτσινάς', 'Kalamata', 'Left Midfielder', 1082);
insert into player (name, last_name, team, position, minutes) values ('Νικήτας', 'Παναγούλης', 'Kavala', 'Right Back', 150);
insert into player (name, last_name, team, position, minutes) values ('Ρομπέρτο', 'Κατράκης', 'Levadiakos', 'Right Back', 3771);
insert into player (name, last_name, team, position, minutes) values ('Παναγιώτης', 'Ευθυμιάδης', 'AEK', 'Attacking Midfielder', 367);
insert into player (name, last_name, team, position, minutes) values ('Παύλος', 'Δημαράς', 'Panathinaikos', 'Attacking Midfielder', 1990);
insert into player (name, last_name, team, position, minutes) values ('Βασίλης', 'Ευγενίδης', 'PAOK', 'Defensive Midfielder', 2470);
insert into player (name, last_name, team, position, minutes) values ('Νικόλαος', 'Κεχαγιάς', 'Olympiacos', 'Center Forward', 967);
insert into player (name, last_name, team, position, minutes) values ('Σόλων', 'Πάνου', 'Aris', 'Center Forward', 1520);
insert into player (name, last_name, team, position, minutes) values ('Σέργιος', 'Πετράκος', 'Volos', 'Defensive Midfielder', 3441);
insert into player (name, last_name, team, position, minutes) values ('Χαρίτος', 'Παπακώστας', 'Atromitos', 'Left Midfielder', 4955);
insert into player (name, last_name, team, position, minutes) values ('Σόλων', 'Σκυλακάκης', 'Asteras Tripolis', 'Center Forward', 3071);
insert into player (name, last_name, team, position, minutes) values ('Θεοφάνης', 'Πολίτης', 'OFI Crete', 'Left Midfielder', 1198);
insert into player (name, last_name, team, position, minutes) values ('Παύλος', 'Φωτόπουλος', 'PAS Giannina', 'Left Midfielder', 339);
insert into player (name, last_name, team, position, minutes) values ('Νικήτας', 'Πετράκος', 'Ionikos', 'Center Midfielder', 410);
insert into player (name, last_name, team, position, minutes) values ('Άγγελος', 'Ευθυμιάδης', 'PAS Lamia', 'Goal Keeper', 3954);
insert into player (name, last_name, team, position, minutes) values ('Οδυσσέας', 'Αλαφούζος', 'Panserraikos', 'Left Back', 3093);
insert into player (name, last_name, team, position, minutes) values ('Μάριος', 'Βούλγαρης', 'AEL', 'Center Forward', 3704);
insert into player (name, last_name, team, position, minutes) values ('Ισίδωρος', 'Ψωμιάδης', 'Panetolikos', 'Right Back', 3252);
insert into player (name, last_name, team, position, minutes) values ('Δαμιανός', 'Φλέσσας', 'Almopos Aridea', 'Center Midfielder', 489);
insert into player (name, last_name, team, position, minutes) values ('Ιωσήφ', 'Γεωργαντάς', 'Egaleo', 'Right Wing', 2328);
insert into player (name, last_name, team, position, minutes) values ('Ερμής', 'Δασκαλάκης', 'Apollon Smyrnis', 'Defensive Midfielder', 4085);
insert into player (name, last_name, team, position, minutes) values ('Νικόλαος', 'Δασκαλάκης', 'Kalamata', 'Goal Keeper', 113);
insert into player (name, last_name, team, position, minutes) values ('Θωμάς', 'Διδασκάλου', 'Kavala', 'Left Midfielder', 2492);
insert into player (name, last_name, team, position, minutes) values ('Θεοκλής', 'Τσιώλης', 'Levadiakos', 'Right Midfielder', 465);
insert into player (name, last_name, team, position, minutes) values ('Θεοκλής', 'Τσακίρης', 'AEK', 'Goal Keeper', 4926);
insert into player (name, last_name, team, position, minutes) values ('Λυκούργος', 'Ευθυμιάδης', 'Panathinaikos', 'Center Midfielder', 2565);
insert into player (name, last_name, team, position, minutes) values ('Χρήστος', 'Πασαλίδης', 'PAOK', 'Defensive Midfielder', 4786);
insert into player (name, last_name, team, position, minutes) values ('Αντώνης', 'Βλαβιανός', 'Olympiacos', 'Right Back', 1824);
insert into player (name, last_name, team, position, minutes) values ('Δημήτρης', 'Κατράκης', 'Aris', 'Right Back', 4527);
insert into player (name, last_name, team, position, minutes) values ('Πάρις', 'Κεχαγιάς', 'Volos', 'Right Wing', 2285);
insert into player (name, last_name, team, position, minutes) values ('Ορφέας', 'Σαμαράς', 'Atromitos', 'Left Back', 4920);
insert into player (name, last_name, team, position, minutes) values ('Χαρίλαος', 'Κυπραίος', 'Asteras Tripolis', 'Attacking Midfielder', 4894);
insert into player (name, last_name, team, position, minutes) values ('Ισίδωρος', 'Αλαφούζος', 'OFI Crete', 'Right Midfielder', 1500);
insert into player (name, last_name, team, position, minutes) values ('Λάζαρος', 'Κορνάρος', 'PAS Giannina', 'Goal Keeper', 2973);
insert into player (name, last_name, team, position, minutes) values ('Νικήτας', 'Δενδρινός', 'Ionikos', 'Right Back', 2924);
insert into player (name, last_name, team, position, minutes) values ('Δαμιανός', 'Σκυλακάκης', 'PAS Lamia', 'Left Back', 2150);
insert into player (name, last_name, team, position, minutes) values ('Σέργιος', 'Σκλαβούνος', 'Panserraikos', 'Right Back', 1847);
insert into player (name, last_name, team, position, minutes) values ('Χαρίλαος', 'Φλέσσας', 'AEL', 'Center Forward', 2282);
insert into player (name, last_name, team, position, minutes) values ('Απόστολος', 'Αλεξίου', 'Panetolikos', 'Left Back', 2890);
insert into player (name, last_name, team, position, minutes) values ('Πέτρος', 'Κορωναίος', 'Almopos Aridea', 'Right Wing', 2098);
insert into player (name, last_name, team, position, minutes) values ('Πάρις', 'Σημηριώτης', 'Egaleo', 'Left Wing', 2890);
insert into player (name, last_name, team, position, minutes) values ('Αλέξανδρος', 'Σκαρβέλης', 'Apollon Smyrnis', 'Left Back', 1139);
insert into player (name, last_name, team, position, minutes) values ('Στέφανος', 'Ανδρεάδης', 'Kalamata', 'Center Midfielder', 2966);
insert into player (name, last_name, team, position, minutes) values ('Ιωάννης', 'Κολιάτσος', 'Kavala', 'Center Forward', 1676);
insert into player (name, last_name, team, position, minutes) values ('Κλέαρχος', 'Σπανού', 'Levadiakos', 'Goal Keeper', 4913);
insert into player (name, last_name, team, position, minutes) values ('Ιωσήφ', 'Βουτσινάς', 'AEK', 'Right Midfielder', 1052);
insert into player (name, last_name, team, position, minutes) values ('Γεώργιος', 'Ανδρέου', 'Panathinaikos', 'Left Back', 3143);
insert into player (name, last_name, team, position, minutes) values ('Αλέξανδρος', 'Κεχαγιά', 'PAOK', 'Center Back', 1386);
insert into player (name, last_name, team, position, minutes) values ('Αντώνης', 'Σταύρου', 'Olympiacos', 'Right Midfielder', 2249);
insert into player (name, last_name, team, position, minutes) values ('Ιωάννης', 'Σαμαράς', 'Aris', 'Left Midfielder', 2683);
insert into player (name, last_name, team, position, minutes) values ('Πέτρος', 'Βούλγαρης', 'Volos', 'Center Midfielder', 89);
insert into player (name, last_name, team, position, minutes) values ('Θεοφάνης', 'Αλαφούζος', 'Atromitos', 'Center Midfielder', 3189);
insert into player (name, last_name, team, position, minutes) values ('Ορφέας', 'Κοφινάς', 'Asteras Tripolis', 'Center Forward', 4771);
insert into player (name, last_name, team, position, minutes) values ('Σέργιος', 'Πολίτης', 'OFI Crete', 'Goal Keeper', 3864);
insert into player (name, last_name, team, position, minutes) values ('Δήμος', 'Δέδες', 'PAS Giannina', 'Left Midfielder', 687);
insert into player (name, last_name, team, position, minutes) values ('Στέφανος', 'Σπανού', 'Ionikos', 'Center Midfielder', 4334);
insert into player (name, last_name, team, position, minutes) values ('Ιωάννης', 'Σπανού', 'PAS Lamia', 'Left Back', 909);
insert into player (name, last_name, team, position, minutes) values ('Θεοφάνης', 'Δέδες', 'Panserraikos', 'Center Back', 4997);
insert into player (name, last_name, team, position, minutes) values ('Πάρις', 'Σημηριώτης', 'AEL', 'Right Wing', 609);
insert into player (name, last_name, team, position, minutes) values ('Ιωάννης', 'Γεωργαντάς', 'Panetolikos', 'Center Midfielder', 20);
insert into player (name, last_name, team, position, minutes) values ('Ορφέας', 'Διδασκάλου', 'Almopos Aridea', 'Right Wing', 3369);
insert into player (name, last_name, team, position, minutes) values ('Ιωσήφ', 'Πετράκος', 'Egaleo', 'Left Wing', 1883);
insert into player (name, last_name, team, position, minutes) values ('Αντώνης', 'Φλέσσας', 'Apollon Smyrnis', 'Defensive Midfielder', 1115);
insert into player (name, last_name, team, position, minutes) values ('Πολύκαρπος', 'Αλιβιζάτος', 'Kalamata', 'Left Back', 408);
insert into player (name, last_name, team, position, minutes) values ('Στέφανος', 'Σαμαράς', 'Kavala', 'Left Wing', 969);
insert into player (name, last_name, team, position, minutes) values ('Ρήγας', 'Γεωργαντάς', 'Levadiakos', 'Goal Keeper', 4225);
insert into player (name, last_name, team, position, minutes) values ('Παύλος', 'Δουρέντης', 'AEK', 'Right Back', 2179);
insert into player (name, last_name, team, position, minutes) values ('Αφεντούλης', 'Κορωναίος', 'Panathinaikos', 'Center Back', 783);
insert into player (name, last_name, team, position, minutes) values ('Απόστολος', 'Φανουράκης', 'PAOK', 'Left Wing', 396);
insert into player (name, last_name, team, position, minutes) values ('Θεοκλής', 'Κοτσοβός', 'Olympiacos', 'Center Forward', 1131);
insert into player (name, last_name, team, position, minutes) values ('Λεωνίδας', 'Κοκκινάκης', 'Aris', 'Defensive Midfielder', 4597);
insert into player (name, last_name, team, position, minutes) values ('Αχιλλέας', 'Κεδίκογλου', 'Volos', 'Left Midfielder', 2192);
insert into player (name, last_name, team, position, minutes) values ('Άγγελος', 'Πολίτης', 'Atromitos', 'Attacking Midfielder', 1978);
insert into player (name, last_name, team, position, minutes) values ('Γεώργιος', 'Σκλάβος', 'Asteras Tripolis', 'Attacking Midfielder', 1070);
insert into player (name, last_name, team, position, minutes) values ('Απόστολος', 'Δασκαλάκης', 'OFI Crete', 'Defensive Midfielder', 1140);
insert into player (name, last_name, team, position, minutes) values ('Αναστάσιος', 'Φλέσσας', 'PAS Giannina', 'Center Midfielder', 40);
insert into player (name, last_name, team, position, minutes) values ('Ρομπέρτο', 'Βλαβιανός', 'Ionikos', 'Goal Keeper', 187);
insert into player (name, last_name, team, position, minutes) values ('Οδυσσέας', 'Ψωμιάδης', 'PAS Lamia', 'Center Forward', 1275);
insert into player (name, last_name, team, position, minutes) values ('Αλέξανδρος', 'Κορωναίος', 'Panserraikos', 'Center Forward', 3503);
insert into player (name, last_name, team, position, minutes) values ('Κλεάνθης', 'Κεδίκογλου', 'AEL', 'Left Midfielder', 178);
insert into player (name, last_name, team, position, minutes) values ('Απόστολος', 'Ταμτάκος', 'Panetolikos', 'Right Wing', 379);
insert into player (name, last_name, team, position, minutes) values ('Ιωάννης', 'Δουρέντης', 'Almopos Aridea', 'Center Midfielder', 2810);
insert into player (name, last_name, team, position, minutes) values ('Δημήτρης', 'Κορνάρος', 'Egaleo', 'Center Forward', 4927);
insert into player (name, last_name, team, position, minutes) values ('Ερμής', 'Σταύρου', 'Apollon Smyrnis', 'Right Midfielder', 3121);
insert into player (name, last_name, team, position, minutes) values ('Ρομπέρτο', 'Πετράκος', 'Kalamata', 'Goal Keeper', 2289);
insert into player (name, last_name, team, position, minutes) values ('Παναγιώτης', 'Σταύρου', 'Kavala', 'Attacking Midfielder', 4385);
insert into player (name, last_name, team, position, minutes) values ('Αχιλλέας', 'Ευθυμιάδης', 'Levadiakos', 'Right Wing', 2741);
insert into player (name, last_name, team, position, minutes) values ('Θεοκλής', 'Φωτόπουλος', 'AEK', 'Left Midfielder', 2555);
insert into player (name, last_name, team, position, minutes) values ('Παύλος', 'Κοκκινάκης', 'Panathinaikos', 'Defensive Midfielder', 3713);
insert into player (name, last_name, team, position, minutes) values ('Παύλος', 'Παχής', 'PAOK', 'Center Midfielder', 3463);
insert into player (name, last_name, team, position, minutes) values ('Σεραφείμ', 'Βέλλος', 'Olympiacos', 'Left Midfielder', 4187);
insert into player (name, last_name, team, position, minutes) values ('Ρομπέρτο', 'Σπανός', 'Aris', 'Left Wing', 4261);
insert into player (name, last_name, team, position, minutes) values ('Δαμιανός', 'Σκλάβος', 'Volos', 'Center Midfielder', 454);
insert into player (name, last_name, team, position, minutes) values ('Χρήστος', 'Γιαλαμάς', 'Atromitos', 'Right Wing', 4177);
insert into player (name, last_name, team, position, minutes) values ('Κώστας', 'Κορομηλάς', 'Asteras Tripolis', 'Right Back', 3139);
insert into player (name, last_name, team, position, minutes) values ('Αλέξιος', 'Σκλάβος', 'OFI Crete', 'Right Back', 324);
insert into player (name, last_name, team, position, minutes) values ('Ρήγας', 'Τσουκαλάς', 'PAS Giannina', 'Center Back', 3680);
insert into player (name, last_name, team, position, minutes) values ('Νικήτας', 'Σταύρου', 'Ionikos', 'Right Wing', 1230);
insert into player (name, last_name, team, position, minutes) values ('Ρήγας', 'Βογιατζής', 'PAS Lamia', 'Center Midfielder', 2532);
insert into player (name, last_name, team, position, minutes) values ('Χρήστος', 'Τούντας', 'Panserraikos', 'Center Midfielder', 3800);
insert into player (name, last_name, team, position, minutes) values ('Πέτρος', 'Σκυλακάκης', 'AEL', 'Center Midfielder', 4097);
insert into player (name, last_name, team, position, minutes) values ('Σαράντος', 'Κονδύλης', 'Panetolikos', 'Left Midfielder', 4421);
insert into player (name, last_name, team, position, minutes) values ('Χρήστος', 'Πάνου', 'Almopos Aridea', 'Right Midfielder', 1573);
insert into player (name, last_name, team, position, minutes) values ('Σέργιος', 'Σκλαβούνος', 'Egaleo', 'Right Back', 4728);
insert into player (name, last_name, team, position, minutes) values ('Αχιλλέας', 'Κορομηλάς', 'Apollon Smyrnis', 'Defensive Midfielder', 2508);
insert into player (name, last_name, team, position, minutes) values ('Αλέξανδρος', 'Γεωργιάδης', 'Kalamata', 'Right Wing', 3918);
insert into player (name, last_name, team, position, minutes) values ('Αθανάσιος', 'Κεχαγιάς', 'Kavala', 'Left Back', 1440);
insert into player (name, last_name, team, position, minutes) values ('Παναγιώτης', 'Σκλάβος', 'Levadiakos', 'Attacking Midfielder', 2152);
insert into player (name, last_name, team, position, minutes) values ('Δημήτρης', 'Ανδρέου', 'AEK', 'Left Back', 295);
insert into player (name, last_name, team, position, minutes) values ('Θεοφάνης', 'Κονδύλης', 'Panathinaikos', 'Left Midfielder', 1133);
insert into player (name, last_name, team, position, minutes) values ('Χαρίλαος', 'Κολιάτσος', 'PAOK', 'Center Back', 97);
insert into player (name, last_name, team, position, minutes) values ('Νικήτας', 'Τσόκος', 'Olympiacos', 'Left Back', 4911);
insert into player (name, last_name, team, position, minutes) values ('Κλεάνθης', 'Αλιβιζάτος', 'Aris', 'Center Back', 2831);
insert into player (name, last_name, team, position, minutes) values ('Ισαάκ', 'Κεδίκογλου', 'Volos', 'Right Wing', 4126);
insert into player (name, last_name, team, position, minutes) values ('Αλέξιος', 'Αναστασίου', 'Atromitos', 'Left Midfielder', 1146);
insert into player (name, last_name, team, position, minutes) values ('Λεωνίδας', 'Σκυλακάκης', 'Asteras Tripolis', 'Attacking Midfielder', 764);
insert into player (name, last_name, team, position, minutes) values ('Κίμων', 'Ιωαννίδης', 'OFI Crete', 'Right Midfielder', 4933);
insert into player (name, last_name, team, position, minutes) values ('Χρήστος', 'Γεωργίου', 'PAS Giannina', 'Defensive Midfielder', 1721);
insert into player (name, last_name, team, position, minutes) values ('Ιπποκράτης', 'Αλιβιζάτος', 'Ionikos', 'Attacking Midfielder', 2168);
insert into player (name, last_name, team, position, minutes) values ('Πολύκαρπος', 'Βέλλος', 'PAS Lamia', 'Goal Keeper', 4506);
insert into player (name, last_name, team, position, minutes) values ('Αλέξανδρος', 'Τούντας', 'Panserraikos', 'Defensive Midfielder', 2160);
insert into player (name, last_name, team, position, minutes) values ('Άγγελος', 'Δελής', 'AEL', 'Left Midfielder', 796);
insert into player (name, last_name, team, position, minutes) values ('Βασίλης', 'Ευθυμιάδης', 'Panetolikos', 'Left Back', 2690);
insert into player (name, last_name, team, position, minutes) values ('Πολύκαρπος', 'Ευταξίας', 'Almopos Aridea', 'Defensive Midfielder', 3015);
insert into player (name, last_name, team, position, minutes) values ('Δημήτρης', 'Αναστασίου', 'Egaleo', 'Center Back', 1279);
insert into player (name, last_name, team, position, minutes) values ('Σωτήριος', 'Πασαλίδης', 'Apollon Smyrnis', 'Defensive Midfielder', 2263);
insert into player (name, last_name, team, position, minutes) values ('Άγγελος', 'Κοκκινάκης', 'Kalamata', 'Defensive Midfielder', 482);
insert into player (name, last_name, team, position, minutes) values ('Αλέξιος', 'Δενδρινός', 'Kavala', 'Left Back', 3591);
insert into player (name, last_name, team, position, minutes) values ('Απόστολος', 'Αντωνιάδης', 'Levadiakos', 'Left Midfielder', 3901);
insert into player (name, last_name, team, position, minutes) values ('Πέτρος', 'Σκλάβος', 'AEK', 'Defensive Midfielder', 2107);
insert into player (name, last_name, team, position, minutes) values ('Αχιλλέας', 'Πάριος', 'Panathinaikos', 'Defensive Midfielder', 4769);
insert into player (name, last_name, team, position, minutes) values ('Λάζαρος', 'Κοτσοβός', 'PAOK', 'Right Wing', 1571);
insert into player (name, last_name, team, position, minutes) values ('Μάρκος', 'Τρικούπης', 'Olympiacos', 'Center Back', 2019);
insert into player (name, last_name, team, position, minutes) values ('Πέτρος', 'Γεωργίου', 'Aris', 'Right Wing', 4116);
insert into player (name, last_name, team, position, minutes) values ('Θεοκλής', 'Αναστασίου', 'Volos', 'Center Back', 1512);
insert into player (name, last_name, team, position, minutes) values ('Παύλος', 'Πυλαρινός', 'Atromitos', 'Left Back', 512);
insert into player (name, last_name, team, position, minutes) values ('Χαρίτος', 'Τσακίρης', 'Asteras Tripolis', 'Right Wing', 4675);
insert into player (name, last_name, team, position, minutes) values ('Νικόλαος', 'Γεωργαντάς', 'OFI Crete', 'Center Forward', 832);
insert into player (name, last_name, team, position, minutes) values ('Πολύκαρπος', 'Δελής', 'PAS Giannina', 'Left Midfielder', 1324);
insert into player (name, last_name, team, position, minutes) values ('Μάρκος', 'Δουρέντης', 'Ionikos', 'Center Midfielder', 3952);
insert into player (name, last_name, team, position, minutes) values ('Παύλος', 'Κοντολέων', 'PAS Lamia', 'Center Forward', 3562);
insert into player (name, last_name, team, position, minutes) values ('Ερμής', 'Κορνάρος', 'Panserraikos', 'Left Wing', 3480);
insert into player (name, last_name, team, position, minutes) values ('Σεραφείμ', 'Τσουκαλάς', 'AEL', 'Center Forward', 1998);
insert into player (name, last_name, team, position, minutes) values ('Ρωμανός', 'Φανουράκης', 'Panetolikos', 'Right Back', 595);
insert into player (name, last_name, team, position, minutes) values ('Αθανάσιος', 'Φλέσσας', 'Almopos Aridea', 'Center Forward', 1701);
insert into player (name, last_name, team, position, minutes) values ('Βασίλης', 'Αναστασίου', 'Egaleo', 'Right Midfielder', 2858);
insert into player (name, last_name, team, position, minutes) values ('Στέφανος', 'Διδασκάλου', 'Apollon Smyrnis', 'Left Midfielder', 4706);
insert into player (name, last_name, team, position, minutes) values ('Πάρις', 'Πολίτης', 'Kalamata', 'Center Back', 71);
insert into player (name, last_name, team, position, minutes) values ('Θεοφάνης', 'Κοτσοβός', 'Kavala', 'Defensive Midfielder', 286);
