insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('AEK', 'Opap Arena', 'Apt 671', 83, 80, 98, 48, 74, 32);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Panathinaikos', 'Apostolos Nikolaidis', 'PO Box 85371', 99, 20, 25, 81, 17, 68);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('PAOK', 'Toubas', 'Room 1091', 34, 99, 77, 21, 66, 1);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Olympiacos', 'Georgios Karaiskakis', 'PO Box 4065', 46, 61, 32, 85, 80, 91);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Aris', 'Kleanthis Vikelidis', 'PO Box 38804', 51, 16, 3, 28, 81, 69);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Volos', 'Panthesalliko', '13th Floor', 99, 3, 52, 56, 99, 70);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Atromitos', 'Peristeriou', 'PO Box 39805', 20, 59, 4, 99, 1, 76);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Asteras Tripolis', 'Theodoros Kolokotronis', '3rd Floor', 30, 14, 32, 99, 79, 73);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('OFI Crete', 'OFI Theodoros Bardinogiannhs', 'Room 758', 83, 15, 9, 63, 26, 29);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('PAS Giannina', 'Zwsimades', 'Apt 1315', 42, 1, 0, 41, 70, 73);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Ionikos', 'Neapolis Nikaias', 'PO Box 89692', 97, 84, 83, 83, 25, 29);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('PAS Lamia', 'Lamias', 'Suite 92', 69, 1, 99, 97, 2, 8);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Panserraikos', 'Serrwn', 'Room 918', 77, 68, 95, 52, 37, 42);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('AEL', 'Arideas', 'Suite 31', 24, 9, 60, 20, 75, 49);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Panetolikos', 'Stauros Maurothalassitis', '16th Floor', 70, 26, 1, 18, 36, 91);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Almopos Aridea', 'Apollona Smyrnis', 'Apt 966', 57, 67, 68, 22, 98, 56);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Egaleo', 'Kalamatas', 'PO Box 29056', 17, 40, 16, 7, 96, 8);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Apollon Smyrnis', 'Anthi Karagiannh', 'Room 14', 93, 64, 91, 86, 88, 51);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Kalamata', 'Labros Katsonis', 'Apt 790', 65, 73, 83, 34, 79, 15);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Kavala', 'Opap Arena', '12th Floor', 34, 25, 15, 14, 64, 61);
insert into team (name, arena, description, home_wins, away_wins, home_losses, away_losses, home_draws, away_draws) values ('Levadiakos', 'Apostolos Nikolaidis', '12th Floor', 32, 69, 52, 60, 55, 3);
